In [102]:
import pandas as pd
pd.set_option('display.max_columns',None)

# df = pd.read_excel(r"C:\Users\lendi\OneDrive\Desktop\DA\reports_1706521616982.xlsx")

df = pd.read_csv(r"C:\Users\lendi\OneDrive\Desktop\DA\reports_1706521616982_csv.csv")
df.columns = df.columns.str.replace(' ','_')

In [103]:
df

,Loan_Id,userId,Registration_Date,Number,Name,Fetched_Name,Email,Loan_count,Employment_information,Platform,Company_Name,Salary,CIBIL_Score,Personal_Loan_Score,Personal_Loan_Account,Overdue_Account,Overdue_Amount,Delay_days,Inquiry_In_Past_30_Days,Total_Outstanding_Balance,Personal_Loan_Outstanding_Balance,CIBIL_Fetched_Attempt,CIBIL_category,City,State,Stage,loanStatus,loanApprovedBy,Decline_reason,Last_CRM,Last_CRM_By,validCibilData
0,754185,a827d7e1-6873-4aa6-91ea-dcaba43d5b22,14-09-2023,9600973979,Preethika H,PREETHIKA S-O HARIDASS,prithika.vp7@gmail.com,-,salaried professional,Android,ACCENTURE SOLUTIONS PVT LTD (CDC-5),-,698,543,221,15,400855,7324,4,869547,869547,24-01-2024,BAD SCORE,chennai,tamil nadu,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,over due,Jigar Banker,YES
1,754133,0c16809a-3031-4a7b-a89c-4e9ca33294eb,23-01-2024,9966022076,Madhu Sudhakar Reddy,SUDHAKARREDDY SUDHAKARREDDY MADHU,sudhakar408@gmail.com,-,salaried,IOS,APOLLO PHARMACIES LIMITED REGIONAL OFFICE KERALA,51700.71,732,707,70,-,-,-,12,2589738,2589738,24-01-2024,BAD SCORE,vijayawada,andhra pradesh,REPAYMENT,APPROVED,System,-,Spoke with the user and he is doing the remain...,Bharat kamaliya,YES
2,-,94187dc3-f6a3-483a-af73-255310fd2f40,24-01-2024,8140352370,Bheda Rajubhai Himmatbhai,BHEDA RAJUBHAI HIMMATBHAI,rajbheda8140352370@gmail.com,-,salaried,Android,-,-,-1,-1,1,-,-,-,3,-,-,24-01-2024,BAD SCORE,-,GUJARAT,NOT_ELIGIBLE,NOT APPLIED,System,-,-,-,YES
3,-,092b546c-fc98-47cd-a53e-03ed87949e58,01-01-2023,9712453007,Abhishek Sarjukumar Gorakh,ABHISHEK SARJUKUMAR GORAKH,abhishekgorakh99@gmail.com,-,-,IOS,STANDARD & POORS SOUTH ASIA SERVICES PRIVATE L...,-,756,666,143,-,-,-,6,1756424,1756424,24-01-2024,MANUAL,-,GUJARAT,REAPPLY,NOT APPLIED,System,-,-,-,YES
4,754186,28468256-7381-4836-aee4-a7c01e4973b6,25-09-2023,8240832606,Dibakar Bardhan,DIBAKAR BARDHAN DIBAKAR BARDHAN,bardhandibakar@gmail.com,4,salaried,Android,TATA CONSULTANCY SERVICES LIMITED,30624.78,817,755,272,-,-,-,1,1353360,1353360,24-01-2024,GOOD SCORE,mugkalyan,west bengal,REPAYMENT,APPROVED,System,-,connect for further process,Priya Khalas,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,760886,073a3666-4552-4a19-aaf2-4c92878ff87d,11-09-2023,8007599149,Kunal Anil Dalvi,KUNAL KUNAL ANIL DALVI,kunaldalvi2314@gmail.com,-,salaried,IOS,APTARA NEW MEDIA PRIVATE LIMITED,-,662,535,22,7,63915,312,3,222045,222045,29-01-2024,BAD SCORE,-,MAHARASHTRA,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,-,-,YES
12339,760912,511f788e-580b-45a1-ba27-a1b959da11c4,12-12-2023,9637430994,Ranjit Balaso salunkhe,SALUNKHE RANJIT BALASO SALUNKHE RANJIT BALASO,salunkheran588@gmail.com,2,salaried,Android,VODAFONE INDIA SERVICES PRIVATE LIMITED,-,739,762,49,-,-,-,7,1582104,1081398,29-01-2024,GOOD SCORE,pune,maharashtra,REAPPLY,NOT APPLIED,System,-,-connect the user over the call he will procee...,Devyansh Prajapati,YES
12340,760888,ebb5b442-17c7-4278-a63d-0d4fd04101ce,29-01-2024,7485038312,Shyam Kishor,MR. SHYAM KISHOR,shyam7485038312@gmail.com,-,self-employed,Android,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,-,775,580,6,-,-,-,5,59802,59802,29-01-2024,MANUAL,-,BIHAR,BANKING,NOT APPLIED,System,-,-,-,YES
12341,-,4c9a9aad-730a-429b-a3fd-bc24f7132ee5,29-01-2024,9108256203,Manoj G S,MANOJ G S MANOJ G S,manoj01gowda@gmail.com,-,salaried,Android,-,-,692,547,137,12,66702,435,2,382237,382237,29-01-2024,BAD SCORE,-,KARNATAKA,NOT_ELIGIBLE,NOT APPLIED,System,-,-,-,YES
12342,-,0faee731-73d1-448e-ae01-7ea8cfd6b6d0,06-09-2022,9959520188,Thammakka Manoj Kumar,THAMMAKKA MANOJ KUMAR MANOJ KUMAR,mm5639502@gmail.com,-,-,Android,FLIPKART INDIA PRIVATE LIMITED,-,609,513,8,4,5871,1449,7,5536,5536,29-01-2024,BAD SCORE,-,TELANGANA,NOT_ELIGIBLE,NOT APPLIED,System,-,-,-,YES

In [142]:
rejected = df[df["loanStatus"]=="REJECTED"]

In [143]:
rejected

,Loan_Id,userId,Registration_Date,Number,Name,Fetched_Name,Email,Loan_count,Employment_information,Platform,Company_Name,Salary,CIBIL_Score,Personal_Loan_Score,Personal_Loan_Account,Overdue_Account,Overdue_Amount,Delay_days,Inquiry_In_Past_30_Days,Total_Outstanding_Balance,Personal_Loan_Outstanding_Balance,CIBIL_Fetched_Attempt,CIBIL_category,City,State,Stage,loanStatus,loanApprovedBy,Decline_reason,Last_CRM,Last_CRM_By,validCibilData
0,754185,a827d7e1-6873-4aa6-91ea-dcaba43d5b22,14-09-2023,9600973979,Preethika H,PREETHIKA S-O HARIDASS,prithika.vp7@gmail.com,-,salaried professional,Android,ACCENTURE SOLUTIONS PVT LTD (CDC-5),-,698,543,221,15,400855,7324,4,869547,869547,24-01-2024,BAD SCORE,chennai,tamil nadu,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,over due,Jigar Banker,YES
5,754187,f8fc0c33-ab19-4a05-9155-e04ae2979a4a,02-01-2024,8328143391,Attipati Srinivasu,ATTIPATI SRINIVASU ATTIPATI SRINIVASU,srinuattipati676@gmail.com,-,salaried,Android,WIPRO LIMITED,-,746,792,41,-,-,-,6,273270,273270,24-01-2024,GOOD SCORE,chellayapalem,andhra pradesh,REAPPLY,REJECTED,System,-,-Tried to connect the user over the call but u...,Devyansh Prajapati,YES
6,754188,ede4802d-1ddd-4bca-b7e4-0db2692493fa,24-01-2024,8810528166,Anmol Agrawal,ANMOL AGRAWAL,agrawal2001.anmol@gmail.com,-,salaried,Android,THINK & LEARN PVT. LTD. - BYJUS,-,719,681,14,-,-,-,7,91736,91736,24-01-2024,MANUAL,sikar,rajasthan,REPAYMENT,REJECTED,Divya Lakhani,User not responding for Further steps,user call connected further step completed,Tinkle Jivani,YES
8,754189,5f21adf8-8c1b-4bb8-8245-dd0046d59a03,24-01-2024,9332304661,SUNIL KARMAKAR,SUNIL KARMAKAR,sunilkarmakar308@gmail.com,-,self-employed,IOS,GLASSFLAM,-,734,743,17,-,-,-,4,109913,109913,24-01-2024,GOOD SCORE,-,WEST BENGAL,REAPPLY,REJECTED,System,-,-,-,YES
9,754190,0cc5b9df-9b4f-4769-b82c-1d87820c6111,03-11-2023,8767479774,Rajindra Tamang,RAJINDRA TAMANG TAMANG,rt7314710@gmail.com,-,salaried,Android,ONGC PETRO ADDITIONS LIMITED,-,761,788,28,-,-,-,11,889772,889772,24-01-2024,BAD SCORE,virar,maharashtra,NOT_ELIGIBLE,REJECTED,Divya Lakhani,Dicey company,user is security guard,Divya Lakhani,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12319,760880,7a33a030-8e34-4314-9934-0b6bf559f108,16-07-2022,9739317523,Avinash K,KENCHAPPA AVINASH AVINASH,nash.k86@gmail.com,-,-,Android,"Oracle India Pvt Ltd, Velocity Block, Prestige...",-,750,619,66,2,11473,49,3,526799,526799,29-01-2024,BAD SCORE,shivamogga,karnataka,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,-,-,YES
12327,760911,5a69888f-784b-40e8-a5a9-6b00a9520400,03-05-2023,8777395094,SHOVIK SENGUPTA,SHOVIK SEN GUPTA S/O S.N. SENGUPTA,shovik.s91@gmail.com,-,salaried,Android,HDFC LIFE INSURANCE COMPANY LIMITED,-,669,529,19,9,49018,6116,7,96647,96647,29-01-2024,BAD SCORE,jalpaiguri,west bengal,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,-,-,YES
12333,760884,11a36af8-9cfa-4014-90ee-f1015168f03f,08-09-2022,7893302016,Macharla Ashok,MACHARLA ASHOK S O RAVINDER,ashokbonny1992@gmail.com,-,salaried professional,Android,HETERO HEALTHCARE LTD.,-,685,527,24,8,92815,3492,6,212831,134219,29-01-2024,BAD SCORE,jangaon,telangana,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,-,-,YES
12336,760885,14f1fc93-d9e9-449f-9179-1c5544c367cd,12-10-2023,9859142303,Anku Dutta,NULL ANKU DUTTA,aankur.dutta@gmail.com,4,salaried,Android,JDB SECURITIES PRIVATE LIMITED,-,706,764,35,-,-,-,6,213031,213031,29-01-2024,GOOD SCORE,guwahati,assam,NOT_ELIGIBLE,REJECTED,System,APPROVED SALARY IS NOT MATCHED WITH STATE SALARY,statement uploded in other docs,Riya Jinde,YES
12338,760886,073a3666-4552-4a19-aaf2-4c92878ff87d,11-09-2023,8007599149,Kunal Anil Dalvi,KUNAL KUNAL ANIL DALVI,kunaldalvi2314@gmail.com,-,salaried,IOS,APTARA NEW MEDIA PRIVATE LIMITED,-,662,535,22,7,63915,312,3,222045,222045,29-01-2024,BAD SCORE,-,MAHARASHTRA,NOT_ELIGIBLE,REJECTED,System,BAD CIBIL SCORE,-,-,YES

In [275]:
# cibil_rejected_650_700 = pd.DataFrame(columns=rejected.columns)
cibil_rejected_650_700 = []

for i,row in rejected.iterrows():
    if row.CIBIL_Score > str(650) and row.CIBIL_Score < str(700):
        cibil_rejected_650_700.append((row))

In [276]:
# for i,row in df.iterrows():
#     if i == 2:
#         print(row)
#         break

In [277]:
# for i in range(5):
#     if i == 2: 
#         print(i)
#         break

In [278]:
s = pd.DataFrame(cibil_rejected_650_700)
csv =s.to_csv('selected_rows.csv', index=False)
print(csv)

None

In [279]:
selected_rows = []

# Iterate through the rows of the 'rejected' DataFrame
for i, row in rejected.iterrows():
    if str(650) < row['CIBIL_Score'] < str(700):
        # Append the row to the 'selected_rows' DataFrame
        selected_rows = selected_rows.append(dict(row))

# Print the selected rows
print(selected_rows)

AttributeError: 'NoneType' object has no attribute 'append'